<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("Magento_Newsletter::css/subscribe.css") ?>">
<div class="block newsletter">
    <div class="content">
        <div class="newsletter-title">SUBSCRIBE TO OUR NEWSLETTER</div>
        <p>For all the news you want special promotions,new product informationand exclusive content.</p>
        <form class="form subscribe"
              novalidate
              action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
              method="post"
              data-mage-init='{"validation": {"errorClass": "mage-error"}}'
              id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label"
                       for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
        <div class="follow">
            <p>By clicking 'Subscribe', you agree to the Terms of Use and Privacy Policy <br/>
                We take your privacy seriously and never share your information.</p>
        </div>

        <div class="socials">
            <a href="https://www.facebook.com/1byone/"><li class="iconfont"></li></a>
            <a href="https://twitter.com/The_1ByOne"><li class="iconfont"></li></a>
            <a href="https://www.youtube.com/user/1BYONEDOORBELLS"><li class="iconfont"></li></a>
            <a href="https://www.instagram.com/1byone_official/"><li class="iconfont"></li></a>
        </div>
    </div>
</div>

<script>
    require(['Magento_Newsletter/js/subscribe'], function (basic) {
        var baseUrl = '<?= $block->getBaseUrl()?>' + 'pub/media/wysiwyg/socials/',
            urlArr = [
                'home_share_fb1.svg',
                'home_share_tw1.svg',
                'home_share_yt1.svg',
                'home_share_ins1.svg',



            ],
            hoverUrlArr = [
                'home_share_fb2.svg',
                'home_share_tw2.svg',
                'home_share_yt2.svg',
                'home_share_ins2.svg',
            ];
        basic(baseUrl, urlArr, hoverUrlArr);
    })
</script>