<?php
/** @var TouchShop\Refund\Block\Refund $block */
?>
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_Basic::css/common.css") ?>">
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_Refund::css/refund.css") ?>">
<form class="refund-form-action-control-container">
    <div class="banner">
        <div>
            <img src="<?php echo $block->getBaseImgUrl('monthlyview.png')?>" alt="">
            <p>30-Day Return</p>
            <p>for Any Reason</p>
        </div>
        <div>
            <img src="<?php echo $block->getBaseImgUrl('anquan.png')?>" alt="">
            <p>18-Month</p>
            <p>Warranty</p>
        </div>
        <div>
            <img src="<?php echo $block->getBaseImgUrl('editor2.png')?>" alt="">
            <p>Lifetime</p>
            <p>Technical Support</p>
        </div>
    </div>
    <div>
        <p>Thank you for visiting our after-sales self-service web page. Here, we hope that you will be able to resolve whatever problems you are experiencing. We're very sorry for whatever inconvenience your purchase may have caused you.</p>
        <p>Please kindly be advised that all of our Anker products come with a hassle-free warranty. You can find your precise warranty period on the literature inside the box or verify with our customer service team. If your product does not meet your needs during this period, please contact us via the refund form below and let us know what we can do to help you.</p>
        <p>Moreover, as a reminder, if you are having trouble using one of our products, you can always refer to the FAQ or Instruction Manuals section on our website, where you may be able to resolve the issue yourself.</p>
        <p>Thank you in advance for all of the information you are providing.</p>
        <h4>Warranty Information Tips</h4>
        <p>Order ID: You can find this in your Amazon account's order history.</p>
        <p>Product Name: You can find this in your Amazon account's order history, as well as on the packaging or manual of the product. Some products come with a watermark showing the model number and/or name of the product.</p>
        <p>Refund or Exchange: Please enter your preference, and we will do our best to accommodate your needs.</p>
        <p>Reason for Request: Enter a short description of the problem here, e.g. "defective".</p>
        <p>Series No.: Depending on the product, the Series No. can be found on the main body of the product or on a charging cable that came with the product.</p>
    </div>
<!--    <div class="refund-nav">-->
<!--        <div class="active">Amazon</div>-->
<!--    </div>-->
    <div class="input-container-title">Contact Information</div>
    <div class="form-group">
            <label for="email">Email Address <span>*</span></label>
            <input name="email" id="refundEmail" placeholder="example@site.com" type="text">
    </div>

    <div class="refund-hint"></div>

    <div class="refund-form-basic-info-container">

        <div class="refund-pwd1">

            <label for="password">Password <span>*</span>
                <input name="password" id="refundPwd1" type="password" required="required" autocomplete="off">
            </label>
        </div>

        <div class="refund-pwd2">

            <label for="password">Please enter your Password again<span>*</span>
                <input name="password" id="refundPwd2" type="password" required="required" autocomplete="off">
            </label>
        </div>
    </div>

    <div class="form-group" id="msg_reasonf">
        <label class="col-sm-2 control-label">Reason for Request</label>
        <div class="col-sm-9">
            <select name="reason" id="msg_reason" class="form-control" required="required">
                <option value="">Select...</option>
                <option value="Danged Upon Arrival">Danged Upon Arrival</option>
                <option value="Deffective">Deffective</option>
                <option value="Sent Wrong Item">Sent Wrong Item</option>
                <option value="Ordered Wrong Item">Ordered Wrong Item</option>
                <option value="No Larger Need">No Larger Need</option>
                <option value="Others">Others</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="msg_goods" class="col-sm-2 control-label">category</label>
        <div class="col-sm-9">
            <select name="goods" id="msg_goods" class="form-control" required="required">
                <option value="">Select</option>
                <option value="antenna">Antenna</option>
                <option value="turntable">Turntable</option>
                <option value="doorbell">Doorbell</option>
                <option value="driveway alarm">Driveway Alarm</option>
                <option value="laser light">Laser Light</option>
                <option value="bubble machine">Bubble Machine</option>
                <option value="blood pressure monitor">Blood Pressure Monitor</option>
                <option value="humidifier">Humidifier</option>
                <option value="scale">Scale</option>
                <option value="keyboard">Keyboard</option>
                <option value="USB hub">USB hub</option>
                <option value="others">Others</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label for="msg_order_number" class="col-sm-2 control-label">Order Number</label>
        <div class="col-sm-9"><input name="order_number" id="msg_order_number" class="form-control" placeholder="Order Number" required="required" type="text">
            <p id="msg_order_notice" class="red" style="display:none;">To better assist your case,please provide the correct Order Number. <span id="msg_order_detail" style="cursor:pointer;color:blue;">Learn More...</span></p>
        </div>
    </div>

    <div class="input-container">
        <input type="radio" name="type" value="exchange" class="exchange"> Exchange
        <input type="radio" checked="checked" name="type" value="refund" class="refund"> Refund
    </div>


    <div class="form-group">
        <label for="msg_message" class="col-sm-2 control-label">Issue Details</label>
        <div class="col-sm-9"><textarea name="message" id="msg_message" class="form-control"></textarea> </div>
    </div>

    <div class="form-address">

    <h1>Your Address</h1>

    <div class="form-group">
        <label class="col-sm-2 control-label">Address</label>
        <div class="col-sm-9">
            <input name="address_string" id="msg_address_string" class="form-control" value="" required="required" type="text">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">State/Province</label>
        <div class="col-sm-9" id="input-province">
            <select name="province_string" id="msg_province_string" class="form-control" required="required">
                <option value="">Please select...</option>
                <option value="Alabama">Alabama</option>
                <option value="Alaska">Alaska</option>
                <option value="American Samoa">American Samoa</option>
                <option value="Arizona">Arizona</option>
                <option value="Arkansas">Arkansas</option>
                <option value="Armed Forces Africa">Armed Forces Africa</option>
                <option value="Armed Forces Americas">Armed Forces Americas</option>
                <option value="Armed Forces Canada">Armed Forces Canada</option>
                <option value="Armed Forces Europe">Armed Forces Europe</option>
                <option value="Armed Forces Middle East">Armed Forces Middle East</option>
                <option value="Armed Forces Pacific">Armed Forces Pacific</option>
                <option value="California">California</option>
                <option value="Colorado">Colorado</option>
                <option value="Connecticut">Connecticut</option>
                <option value="Delaware">Delaware</option>
                <option value="District of Columbia">District of Columbia</option>
                <option value="Federated States Of Micronesia">Federated States Of Micronesia</option>
                <option value="Florida">Florida</option>
                <option value="Georgia">Georgia</option>
                <option value="Guam">Guam</option>
                <option value="Hawaii">Hawaii</option>
                <option value="Idaho">Idaho</option>
                <option value="Illinois">Illinois</option>
                <option value="Indiana">Indiana</option>
                <option value="Iowa">Iowa</option>
                <option value="Kansas">Kansas</option>
                <option value="Kentucky">Kentucky</option>
                <option value="Louisiana">Louisiana</option>
                <option value="Maine">Maine</option>
                <option value="Marshall Islands">Marshall Islands</option>
                <option value="Maryland">Maryland</option>
                <option value="Massachusetts">Massachusetts</option>
                <option value="Michigan">Michigan</option>
                <option value="Minnesota">Minnesota</option>
                <option value="Mississippi">Mississippi</option>
                <option value="Missouri">Missouri</option>
                <option value="Montana">Montana</option>
                <option value="Nebraska">Nebraska</option>
                <option value="Nevada">Nevada</option>
                <option value="New Hampshire">New Hampshire</option>
                <option value="New Jersey">New Jersey</option>
                <option value="New Mexico">New Mexico</option>
                <option value="New York">New York</option>
                <option value="North Carolina">North Carolina</option>
                <option value="North Dakota">North Dakota</option>
                <option value="Northern Mariana Islands">Northern Mariana Islands</option>
                <option value="Ohio">Ohio</option>
                <option value="Oklahoma">Oklahoma</option>
                <option value="Oregon">Oregon</option>
                <option value="Palau">Palau</option>
                <option value="Pennsylvania">Pennsylvania</option>
                <option value="Puerto Rico">Puerto Rico</option>
                <option value="Rhode Island">Rhode Island</option>
                <option value="South Carolina">South Carolina</option>
                <option value="South Dakota">South Dakota</option>
                <option value="Tennessee">Tennessee</option>
                <option value="Texas">Texas</option>
                <option value="Utah">Utah</option>
                <option value="Vermont">Vermont</option>
                <option value="Virgin Islands">Virgin Islands</option>
                <option value="Virginia">Virginia</option>
                <option value="Washington">Washington</option>
                <option value="West Virginia">West Virginia</option>
                <option value="Wisconsin">Wisconsin</option>
                <option value="Wyoming">Wyoming</option>
            </select>
        </div>
    </div>


    <div class="form-group">
        <label class="col-sm-2 control-label">Postalcode</label>
        <div class="col-sm-5">
            <input name="zipcode" id="msg_zipcode" class="form-control" value="" required="required" type="text">
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Country/Province</label>
        <div class="col-sm-9">
            <select name="country" id="msg_country" class="form-control" onchange="change_country(this.options[this.options.selectedIndex].value)">
                <option value="220">United States</option>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Phone</label>
        <div class="col-sm-5">
            <input name="tel" id="msg_tel" class="form-control" value="" required="required" type="text">
        </div>
    </div>
    </div>

    <div class="form-action-btn">
        <button type="reset">RESET</button>
        <button type="button">SUBMIT</button>
    </div>
</form>

<script>
    (function () {
        require(['jquery'], function ($) {
            var formAddress = $(".form-address");

            $(".refund").click(function () {
                formAddress.css("display", "none");
            })

            $(".exchange").click(function () {
                formAddress.css("display", "block")
            })
        })
    })()
</script>

<script>
    require(['jquery', 'ajax', 'bindQuickAutoLogin'], function ($, ajax, binder) {
        let data = <?= $block->getLoginInfo()?>;
        let hint = $(".refund-hint");
        hint.text(sessionStorage.getItem("success") || '').css("color", "blue");
        binder.bind(
            data,
            "<?= $block->getBaseUrl()?>",
            $("#refundEmail"),
            $(".refund-form-action-control-container .refund-pwd1"),
            $(".refund-form-action-control-container .refund-pwd2"),
            $("#refundPwd1"),
            $("#refundPwd2"),
            $(".refund-form-action-control-container input"),
            $(".form-action-btn button[type='button']"),
            hint,
            submitFormFun,
        );

        function submitFormFun(email) {
            let result = false;
            ajax.sendAjax(
                false,
                "<?= $block->getFormAction()?>",
                {
                    email: email,
                },
                function (res) {
                    console.log("form submit", res);
                    if (res.status_code == 200) {
                        result = true;
                    } else {
                        hint.text(res.error_message);
                    }
                });
            return result;
        }
    });

</script>