<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var Magento\Framework\View\Element\Template $block
 */

?>
<?php

/**
 *  General template for displaying group of blocks devided into sections
 */

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("Magento_Theme::css/sections.css") ?>">

<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')): ?>
    <div class="sections <?= /* @escapeNotVerified */
    $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /* @escapeNotVerified */
        $groupCss ?>-items" data-mage-init='<?= /* @escapeNotVerified */
        $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name): ?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html) && ($block->getUseForce() != true)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?= /* @escapeNotVerified */
                $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /* @escapeNotVerified */
                    $groupCss ?>-item-switch" data-toggle="switch" href="#<?= /* @escapeNotVerified */
                    $alias ?>"><?= /* @escapeNotVerified */
                        $label ?></a>
                </div>
                <div class="section-item-content <?= /* @escapeNotVerified */
                $groupCss ?>-item-content" id="<?= /* @escapeNotVerified */
                $alias ?>" data-role="content"><?= /* @escapeNotVerified */
                    $html ?></div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<script>
    (function () {
        require(['jquery', 'jquery/ui'], function ($) {
            console.log("sections script in");

            var pInfoNav = $(".data.item.title");
            var toolbar = $(".page-header");
            var menubar = $(".sections.nav-sections");
            var isOver = -1;
            console.log(isOver);

            $(window).scroll(function (e) {
                var docTop = $(document).scrollTop();
                var productInfo = $(".product.info.detailed");

                // console.log(docTop, productInfo.offset().top);

                // isOver = productInfo.offset().top - docTop -130;
                // console.log(isOver);


                // if(isOver <= 0) {
                //     pInfoNav.css("position", "fixed");
                // }


                scrollFunc(e, isOver);
                // console.log(toolbar.height());
                // console.log(productInfo.offset().top, productInfo.scrollTop());
                if (docTop >= 30) {
                    $(".sections").css("background-color", "rgba(255,255,255,0.8)");
                    $(".navigation .level0 > .level-top").addClass("nav-background-grey");
                } else {
                    $(".sections").css("background-color", "rgba(255,255,255,0)");
                    $(".navigation .level0 > .level-top").removeClass("nav-background-grey");
                }
            });


            var scrollFunc = function (e, isOver) {



                console.log(isOver);

                e = e || window.event;
                if (e.wheelDelta) {  //第一步：先判断浏览器IE，谷歌滑轮事件
                    if (e.wheelDelta > 0) { //当滑轮向上滚动时
                        console.log("滑轮向上滚动");
                    }
                    if (e.wheelDelta < 0) { //当滑轮向下滚动时
                        console.log("滑轮向下滚动");
                    }
                } else if (e.detail) {  //Firefox滑轮事件
                    if (e.detail> 0) { //当滑轮向上滚动时
                        console.log("滑轮向上滚动");
                    }
                    if (e.detail< 0) { //当滑轮向下滚动时
                        console.log("滑轮向下滚动");
                    }
                }
            }
            // //给页面绑定滑轮滚动事件
            // if (document.addEventListener) {//firefox
            //     document.addEventListener('DOMMouseScroll', scrollFunc, false);
            // }
            // //滚动滑轮触发scrollFunc方法  //ie 谷歌
            // window.onmousewheel = document.onmousewheel = scrollFunc;









        })
    })()
</script>



<script>

</script>

