<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var Magento\Framework\View\Element\Template $block
 */

?>
<?php

/**
 *  General template for displaying group of blocks devided into sections
 */

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("Magento_Theme::css/sections.css") ?>">

<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')): ?>
    <div class="sections <?= /* @escapeNotVerified */
    $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?= /* @escapeNotVerified */
        $groupCss ?>-items" data-mage-init='<?= /* @escapeNotVerified */
        $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name): ?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html) && ($block->getUseForce() != true)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?= /* @escapeNotVerified */
                $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?= /* @escapeNotVerified */
                    $groupCss ?>-item-switch" data-toggle="switch" href="#<?= /* @escapeNotVerified */
                    $alias ?>"><?= /* @escapeNotVerified */
                        $label ?></a>
                </div>
                <div class="section-item-content <?= /* @escapeNotVerified */
                $groupCss ?>-item-content" id="<?= /* @escapeNotVerified */
                $alias ?>" data-role="content"><?= /* @escapeNotVerified */
                    $html ?></div>
            <?php endforeach; ?>
        </div>
        <div class="back-top"></div>
    </div>
<?php endif; ?>

<script>
    (function () {
        require(['jquery', 'jquery/ui'], function ($) {

            var pInfoNav = $(".data.item.title");
            var toolbar = $(".page-header");
            var menubar = $(".sections.nav-sections");
            var topmenu = $(".top-menu li a");
            var backTop = $(".back-top");


            $(window).scroll(function (e) {
                var docTop = $(document).scrollTop();
                var productInfo = $(".product.info.detailed");
                if (docTop >= 30) {
                    $(".sections").css("background-color", "rgba(255,255,255,0.95)");
                    topmenu.addClass("nav-background-grey");
                } else {
                    if(!topMenuIsHoverd) {
                        $(".sections").css("background-color", "rgba(255,255,255,0)");
                        topmenu.removeClass("nav-background-grey");
                    }
                }

                if(docTop >= 600) {
                    backTop.css("display", "block");
                }else {
                    backTop.css("display", "none");
                }

            });

            backTop.click(function () {
                $(document).scrollTop(0);
                // $(this).css("display", "none");
            });

        })
    })()
</script>



<script>

</script>

