<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \TouchShop\Touch1byone\Plugin\Block\Topmenu
 */

$topmenus = $block->getTopMenus();


?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("Magento_Theme::css/topmenu.css") ?>">

<nav class="navigation" data-action="navigation">
    <ul class="top-menu">
        <div class="top-menu-wrapper home"><li><a href="<?= $block->getBaseUrl()?>">Home</a></li></div>
        <?php foreach ($topmenus as $menu): ?>
            <div class="top-menu-wrapper">
                <li data-src="<?= $menu['image_url'] ?>"><a href="<?= $menu['url'] ?>"><?= $menu['label'] ?></a></li>
                <div class="menu-info">
                    <div class="submenu">
                        <?php foreach ($menu['submenus'] as $submenuGroup): ?>
                            <ul>
                                <?php foreach ($submenuGroup as $submenu): ?>
                                    <li data-src="<?= $submenu['image_url'] ?>"><a
                                                href="<?= $submenu['url'] ?>"><?= $submenu['label'] ?></a></li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endforeach; ?>
                    </div>

                    <div class="menu-image">
                        <img class="menu-tag-img" style="display: block;height: 140px;" src="<?= $menu['image_url'] ?>" alt="">
                    </div>

                    <?php if (isset($menu['additions'])): ?>
                        <div class="Brand-container">
                            <div class="Brand-title">Brand</div>
                            <div class="Brand-content">
                                <?php foreach ($menu['additions'] as $brand): ?>
                                    <a href="<?= $brand['url'] ?>"><?= $brand['label'] ?></a>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </ul>
<!--    <div class="menu-info-cover"></div>-->
</nav>


<script>
    var topMenuIsHoverd = false;

    (function () {
        require(['jquery', 'Magento_Theme/js/preload', 'jquery/ui' ], function ($, preload) {
            $(document).ready(function () {
                    var li = $("nav>ul li");
                    var menuInfo = $('.menu-info');
                    var topMenuItem = $(".top-menu-wrapper > li");
                    var sections = $(".sections");
                    // var menuInfoCover = $(".menu-info-cover");
                    var navigation = $("nav.navigation");
                    var isHoverd = false;
                    var submenu = $(".submenu ul li");
                    var menuImg = $(".menu-image");
                    var topmenu = $(".top-menu li a");
                    var menuImgContainer = $(".menu-tag-img");
                    var navCore = $(".section-items");
                    li.on({
                        mouseover: function (e) {
                            if ($(this).children("ul").length != 0) {
                                $(this).children("ul").css({"display": "flex"});
                            }
                        },
                        mouseout: function (e) {
                            $(this).children("ul").css("display", "none");
                        }
                    });

                    // console.log($(".navigation ul li"));
                    // menuInfoCover.hide();
                    topMenuItem.click(function (e) {

                        let topMenuItemSubMenu = $(e.target).parent().parent().find(".submenu > ul");
                        let hasSubmenu = topMenuItemSubMenu.children().length > 0 ? true : false;
                        // console.log("$(e):",$(e.target), $(e.target).parent(),  topMenuItemSubMenu, topMenuItemSubMenu.children(), hasSubmenu);
                        if ($(window).width() < 525 && hasSubmenu) {
                            e.preventDefault();
                            $(e.target).parent().next().toggleClass("force-active");
                        }

                    });


                    // A-->B
                    topMenuItem.on({

                        mouseover: function (e) {
                            if ($(window).width() > 525) {
                                // $(this).css("color", "#8d131c");
                                if ($(this).parent().find(".submenu ul").children().length) {
                                    topMenuIsHoverd = true;
                                    topmenu.addClass("nav-background-grey");
                                    navCore.css({
                                        "border-bottom": "1px solid #D8D8D8"
                                    });
                                    menuInfo.removeClass("active");
                                    // menuInfoCover.css("display", "block");
                                    // menuInfoCover.animate({height: "270px"}, 500);
                                    $(this).next().addClass("active");

                                    let submenuLastItem = $(this).parents(".top-menu-wrapper").find(".menu-info > div:last-child");
                                    let submenuLastItemHeight = submenuLastItem.offset().top + submenuLastItem.height();
                                    console.log("submenuLastItem: ",submenuLastItem, submenuLastItemHeight);
                                    sections.css({
                                        "background-color": "rgba(255, 255, 255, 0.95)",
                                        "height": "350px"
                                    });
                                } else {
                                    topMenuIsHoverd = false;
                                    sections.css("border-bottom", "none");
                                    if ($(document).scrollTop() <= 30) {
                                        topmenu.removeClass("nav-background-grey");
                                        sections.css("background-color", "rgba(255,255,255, 0)");
                                    }

                                    // menuInfoCover.css("display", "none");
                                    // menuInfoCover.animate({height: "0"}, 500);
                                    menuInfo.removeClass("active");
                                }
                            }
                        }
                    })
                    ;
                    // B-->A
                    sections.on({
                        mouseleave: function (e) {
                            setTimeout(function () {
                                if (!isHoverd) {

                                    topMenuIsHoverd = false;
                                    // sections.css("border-bottom", "none");
                                    if ($(document).scrollTop() <= 30) {
                                        topmenu.removeClass("nav-background-grey");
                                        sections.css("height", "0");
                                    } else {
                                        sections.css("height", "80px");
                                    }

                                    navCore.css({
                                        "border-bottom": "none"
                                    });
                                    // menuInfoCover.css("display", "none");
                                    // menuInfoCover.animate({height: "0"}, 500);
                                    menuInfo.removeClass("active");
                                }
                            }, 1);
                        }
                    });
                    menuInfo.hover(function () {
                        isHoverd = true;
                    }, function () {
                        isHoverd = false;
                    });


                    $(".top-menu li").mouseover(function () {
                        console.log(this);
                        // if(menuImgContainer.attr("src") != $(this).attr("data-src"))
                        menuImgContainer.attr('src', $(this).attr("data-src"));
                    });

                    //image preload
                    var imgSrcArr = [];
                    $(".top-menu li").each(function (index, e) {
                        imgSrcArr.push($(e).attr("data-src"));
                    });
                    console.log(imgSrcArr);

                    preload(imgSrcArr);
                }
            )
        })
    })()
</script>
