<?php
/** @var TouchShop\PowerUser\Block\PowerUser $block */

?>
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_Basic::css/common.css") ?>">
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_PowerUser::css/PowerUser.css") ?>">
<div class="blank"></div>
<div class="power-user-banner">
    <img src="<?php echo $block->getBaseImgUrl('banner_superuser.jpg') ?>" alt="">
    <h2>Super User</h2>
</div>
<form action="<?php echo $block->getFormAction() ?>" method="post" class="power-user-form">
    <h2>Make 1byone better. Make life better</h2>
    <div class="input-container-title"><p>At 1byone,we create and develop products to make people's lives better, easier
            and more fulfilling.We approach every detail from a user's perspective to improve our technology, our
            products and our service.</p>
        <p>For that, we start the Super User programs to learn more about people's idea and needs about 1byone
            product.</p>
        <p>Join Super Users, you get free or exclusive discounts, loyalty rewards and other special benefits from
            1byone.</p>
    </div>

    <div class="input-container">
        <label for="email">I am interested in </label>
        <div class="input-container input-container-full">
            <div class="input-checkbox-container">
                <div><input type="checkbox" name="interests[]" value="TV Accessories"> TV Accessories</div>
                <div><input type="checkbox" name="interests[]" value="Home Decoration"> Home Decoration</div>
                <div><input type="checkbox" name="interests[]" value="Stage Lighting & Effects"> Stage Lighting &
                    Effects
                </div>
                <div><input type="checkbox" name="interests[]" value="Home Security"> Home Security</div>
                <div><input type="checkbox" name="interests[]" value="Accessories"> Accessories</div>
                <div><input type="checkbox" name="interests[]" value="Power"> Power</div>
                <div><input type="checkbox" name="interests[]" value="Healths"> Health</div>
                <div><input type="checkbox" name="interests[]" value="Audio & Sounds"> Audio & Sounds</div>
            </div>
        </div>

        <label for="email">Country selected </label>
        <div class="input-container input-container-full">
            <div class="input-radio-container">
                <div><input type="radio" name="country" value="United States" checked="checked"> United States</div>
                <div><input type="radio" name="country" value="Canada"> Canada</div>
                <div><input type="radio" name="country" value="United Kingdom"> United Kingdom</div>
                <div><input type="radio" name="country" value="France"> France</div>
                <div><input type="radio" name="country" value="Germany"> Germany</div>
                <div><input type="radio" name="country" value="Spain"> Spain</div>
                <div><input type="radio" name="country" value="Italy"> Italy</div>
            </div>
        </div>
    </div>

    <div class="power-user-description">
        <h2>Q: As a brand-new one, why do I join Super User?</h2>
        <p>A: Super User will receive products from 1byone.
            Super User will have excusive discount codes and rewards.
            Except these,
            Super User usually will be the first one to know more about the latest product.
            Super User may change products of 1byone.</p>

        <h2>Q: Who should apply as a Super User?</h2>
        <p>A: Everyone interested in 1byone and active in social media can apply to be a Super User.Some basic
            requirements for application:
            Social media— Minimum 20K followers and active engagement
            YouTube Channel—Minimum 1K subscribers and high-quality content
            Website / Forum / Blog— Minimum 1K visits daily</p>

        <h2>Q: I have a problem of Super User application?</h2>
        <p>A: If you have any problems with Super User, please send an email to ushelp@1byone.com and we'll reply back to
            you within 3 work days.</p>
    </div>

    <div class="input-container-title form-title">Super User Information</div>

    <div class="input-container input-control-group">
        <div class="form-action-control-container">
            <div class="control1">
                <label for="text">Email address <span>*</span>
                    <input name="email" id="powerUserEmail" type="email" required="required" autocomplete="off">
                    <div class="hint">the required field cannot be empty</div>
                </label>
            </div>
            <div class="power-user-hint"></div>

            <div class="power-user-pwd1">
                <label for="password">Password <span>*</span>
                    <input name="password" id="powerUserPwd1" type="password" required="required" autocomplete="off">
                </label>
            </div>

            <div class="power-user-pwd2">
                <label for="password">Please enter your Password again<span>*</span>
                    <input name="password" id="powerUserPwd2" type="password" required="required" autocomplete="off">
                </label>
            </div>

            <div class="form-action-btn">
                <button type="button">SUBMIT</button>
            </div>
        </div>
    </div>
</form>


<script>
    (function () {
        require(['jquery', 'ajax', 'bindQuickAutoLogin', 'TouchShop_Touch1byone/js/formValidate'], function ($, ajax, bindQuickAutoLogin, formValidater) {
            let data = <?= $block->getAjax()?>;
            let inputCheckBox = $(".input-checkbox-container input");
            let radioBoxes = $(".input-radio-container input");
            let hint = $(".power-user-hint");
            let form = $(".power-user-form");
            let btn = $(".form-action-btn button[type='button']");
            hint.text(sessionStorage.getItem("success") || '').css("color", "blue");
            if (data.vip == 2) {
                // interests
                inputCheckBox.each(function (index, e) {
                    if (data.interests.indexOf($(e).val()) != -1) {
                        $(e).attr("checked", "checked");
                    }
                });
                console.log(data.country);
                radioBoxes.each(function (index, e) {
                    $(e).attr("checked", "");
                    if (data.country == $(e).val()) {
                        $(e).attr("checked", "checked");
                        return false;
                    }
                })


            }

            btn.click(function () {
                formValidater.validateForm(form);
            })

            bindQuickAutoLogin.bind(
                data,    //data
                "<?= $block->getBaseUrl()?>", //baseUrl
                $("#powerUserEmail"),   //email
                $(".form-action-control-container .power-user-pwd1"),   //userPwd1Con
                $(".form-action-control-container .power-user-pwd2"),   //userPwd2Con
                $("#powerUserPwd1"),    //userPwd1
                $("#powerUserPwd2"),    //userPwd2
                $(".form-action-control-container input"),  //formActionInput
                btn,    //submitBtn
                hint,  //hint
                submitForm  //submitFormFunc
            );

            function submitForm(email, customerId) {
                let result = false;
                let url = "<?= $block->getFormAction()?>";
                let interestsArr = [];
                let inputCheckedContainer = $(".input-checkbox-container input:checked");
                inputCheckedContainer.each(function (index, e) {
                    interestsArr.push(e.value);
                });
                let country = $("input[name='country']:checked").val();
                console.log(country);
                let param = {
                    email: email,
                    customerId: customerId,
                    interests: interestsArr,
                    country: country
                };
                ajax.sendAjax(false, url, param, function (res) {
                    console.log("form submit", res);
                    if (res.status_code == 200) {
                        result = true;
                    } else {
                        hint.text(res.error_message);
                    }
                });
                return result;
            }
        })
    })();
</script>
