<?php /**@var TouchShop\Touch1byone\Block\CategoryNavigator $block */ ?>

<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_Basic::css/common.css") ?>">
<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl("TouchShop_Touch1byone::css/index.css") ?>">
<!-- template -->
<!--    <div class="leaf-contianer">-->
<template>
    <div class="leaf-content">
        <div class="tag-name" title="-tag-title-">-tag-</div>
        <div class="icon">
            <img src="<?php echo $block->getImgBaseUrl('arrow.png'); ?>" alt="">
        </div>
    </div>
</template>
<!--    </div>-->

<!-- template end -->
<div class="tree-container" id="tree-container">

</div>

<script>
    (function () {
        function toggle(tag, fn) {
            var status;
            if (tag.classList.contains('active')) {
                tag.classList.remove('active');
                status = false
            } else {
                tag.classList.add('active');
                status = true
            }
            if (fn) status ? (fn.open ? fn.open(tag) : '') : (fn.close ? fn.close(tag) : '')
        }

        function init() {
            // init tree
            var TREE_DATA = <?php echo $block->getCategoryTree()?>;
            var TEMPLATE = document.querySelector('template');

            function createLeaf(dom, data, fater) {
                var div = TEMPLATE.innerHTML;
                var leaf = document.createElement('div');
                leaf.classList.add('leaf-contianer');
                leaf.setAttribute('data-fater', fater)
                // data
                if (!data.children) leaf.innerHTML = div.replace(/-tag-title-/, data.text).replace(/-tag-/, data.text).replace(/icon/, 'icon hide');
                else leaf.innerHTML = div.replace(/-tag-title-/, data.text).replace(/-tag-/, data.text);
                leaf.querySelector('.icon').setAttribute('data-fater', data.text)
                if(data.url) {
                    leaf.querySelector('.tag-name').classList.add('a')
                    leaf.querySelector('.tag-name').onclick = function () {
                        window.open(data.url)
                    }
                }
                dom.appendChild(leaf);

                if (data.children && data.children.length != 0) {
                    for (var j = 0; j < data.children.length; j++) {
                        createLeaf(leaf, data.children[j], data.text)
                    }
                }
            }

            createLeaf(document.querySelector('#tree-container'), TREE_DATA, 'first')

            // add icon click
            var icon = document.querySelectorAll('.tree-container .leaf-content .icon')
            for (var k = 0; k < icon.length; k++) {
                icon[k].onclick = function () {
                    toggle(this, {
                        open: function (params) {
                            var dom = params.parentNode.parentNode.querySelectorAll('.leaf-contianer')
                            var fater = params.getAttribute('data-fater')
                            for (var a = 0; a < dom.length; a++) {
                                if(dom[a].getAttribute('data-fater') == fater)
                                    dom[a].classList.add('active');
                            }
                        },
                        close: function (params) {
                            var dom = params.parentNode.parentNode.querySelectorAll('.leaf-contianer')
                            var fater = params.getAttribute('data-fater')
                            for (var a = 0; a < dom.length; a++) {
                                if(dom[a].getAttribute('data-fater') == fater)
                                    dom[a].classList.remove('active');
                            }
                        }
                    })
                }
            }
        }

        init()
    })()
</script>
