<?php
/**@var Magento\Framework\View\Element\Html\Link\Current $block*/
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Touch1byone::css/foot-links.css")?>">
<div class="footer-links">
    <div class="footer-links-about">
        <ul>
            <li>About Us</li>
            <li>Wholesale</li>
            <li>Blogs</li>
            <li>Promotions</li>
        </ul>
    </div>
    <div class="footer-links-support">
        <ul>
            <li>Support</li>
            <li>FAQ</li>
            <li>Warranty</li>
            <li>Terms and Conditions</li>
            <li>Privacy Policy</li>
        </ul>
    </div>
</div>