<?php
/**@var Magento\Framework\View\Element\Html\Link\Current $block */
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Touch1byone::css/foot-links.css") ?>">
<div class="footer-links">
    <div class="footer-links-about">
        <h1><strong>1byone</strong></h1>
        <ul>
            <li><a href="<?php echo $block->getBaseUrl() . 'about-us' ?>">About Us</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'contact-us' ?>">Contact Us</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'blog.html' ?>">Blog</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'super-user' ?>">Super User</a></li>

        </ul>
    </div>
    <div class="footer-links-support">
        <h1><strong>Support</strong></h1>
        <ul>
            <li><a href="<?php echo $block->getBaseUrl() . 'support' ?>">FAQ</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'refund' ?>">Exchange</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'warranty' ?>">Warranty</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'terms-condition' ?>">Terms and Use</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'privacy-policy' ?>">Privacy Policy</a></li>
        </ul>
    </div>
</div>

