<?php
/**@var Magento\Framework\View\Element\Html\Link\Current $block*/
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Touch1byone::css/foot-links.css")?>">
<div class="footer-links">
    <div class="footer-links-about">
        <h1><strong>company</strong></h1>
        <ul>
            <li><a href="<?php echo $block->getBaseUrl() . 'about-us'?>">About Us</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'wholesale'?>">Wholesale</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'blog.html'?>">Blogs</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'sales'?>">Sales</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'contact-us'?>">Contact Us</a></li>

        </ul>
    </div>
    <div class="footer-links-support">
        <h1><strong>Support</strong></h1>
        <ul>
            <li><a href="<?php echo $block->getBaseUrl() . 'support'?>" >Support</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'faq'?>">FAQ</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'warranty'?>">Warranty</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'terms-condition'?>">Terms and Conditions</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . 'privacy-policy'?>">Privacy Policy</a></li>
        </ul>
    </div>
</div>

