<?php
/** @var TouchShop\Touch1byone\Block\User $block */
//?>
<div class="small-menu">
</div>
<script>
    require(['jquery'], function ($) {
        $(function () {
            var menu = $(".small-menu");
            var baseUrl = '<?= $block->getBaseUrl()?>' + 'pub/media/wysiwyg/menu/',
                urlArr = [
                    'close.svg',
                    'menu.svg'
                ];
            var navIsShowed = true;

            menu.css("background-image", 'url(' + baseUrl + urlArr[1] + ')');
            var nav = $("nav.navigation");
            console.log("screen:", $(window).width());
            if ($(window).width() < 766) {
                nav.hide();
                $(".sections.nav-sections").css("display", "none");
                $(".page-header").css("border-bottom", "none");
                navIsShowed = false;
            }
            $(window).resize(function () {
                if ($(window).width() < 766) {
                    nav.hide();
                    $(".sections.nav-sections").css("display", "none");
                    // $(".page-header").css("border-bottom", "1px solid white");
                } else {
                    nav.show();
                    $(".sections.nav-sections").css("display", "block");
                }
            });
            menu.click(function () {
                if(navIsShowed == false) {
                    menu.css("background-image", 'url(' + baseUrl + urlArr[0] + ')');
                    $(".sections.nav-sections").css("display", "block");
                    $(".page-header").css("border-bottom", "1px solid white");
                    nav.show();
                    navIsShowed = true;
                } else {
                    menu.css("background-image", 'url(' + baseUrl + urlArr[1] + ')');
                    $(".sections.nav-sections").css("display", "none");
                    $(".page-header").css("border-bottom", "none");
                    nav.hide();
                    navIsShowed = false;
                }
            });
        })
    })
</script>
