<?php
/** @var TouchShop\Touch1byone\Block\User $block */
//?>

<?php
///**
// * Copyright © Magento, Inc. All rights reserved.
// * See COPYING.txt for license details.
// */
//
//// @codingStandardsIgnoreFile
//
///** @var \Magento\Customer\Block\Form\Register $block */
//?>


<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Touch1byone::css/user.css") ?>">

<div class="user">
    <div class="user-icon">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20">
            <defs>
                <style>.cls-1 {
                        fill: #333;
                        opacity: 10;
                    }</style>
            </defs>
            <title>source 10</title>
            <g id="le_2" data-name="le2">
                <g id="le1-2" data-name="le1">
                    <rect class="cls-1" width="20" height="20"/>
                    <path fill="white" d="M10,12.08A5.14,5.14,0,1,1,15.09,7,5.14,5.14,0,0,1,10,12.08Zm0-8.72A3.59,3.59,0,1,0,13.54,7,3.59,3.59,0,0,0,10,3.36Z"/>
                    <path fill="white" d="M16.29,18.37a.78.78,0,0,1-.78-.78,5.51,5.51,0,1,0-11,0,.78.78,0,1,1-1.55,0,7.06,7.06,0,1,1,14.12,0A.78.78,0,0,1,16.29,18.37Z"/>
                </g>
            </g>
        </svg>
    </div>

    <div class="user-submenu">
        <ul>
            <li><a href="<?php echo $block->getBaseUrl() . "customer/account/" ?>">Account Info</a></li>
            <li><a href="<?php echo $block->getBaseUrl() . "customer/account/logout" ?>">Log out</a></li>
        </ul>
    </div>
</div>

<script>
    require(['jquery'], function ($) {
        $(function () {
            var socialLoginIcon = $(".third-party-login .btn-social");

            socialLoginIcon.each(function (index, e) {
                let txtArr = $(e).text().trim().split(" ");
                console.log(($(e).contents())[2].nodeValue);
                ($(e).contents())[2].nodeValue = txtArr.pop();
            });


            <?php if ($block->hasLogin()):?>
            $(".user").on({
                mouseover: function () {
                    if ($(window).width() > 525) {
                        $(".user-submenu").css("display", "block");
                        $("#searchBtn pseudo").css("color", "#817a7a");
                    }
                },
                mouseout: function () {
                    if ($(window).width() > 525) {
                        $(".user-submenu").css("display", "none");
                    }
                },
                click: function () {
                    if ($(window).width() <= 525) {
                        $(".user-submenu").css("display", "block");
                        $("#searchBtn pseudo").css("color", "#817a7a");
                    }
                }
            });
            <?php else:?>
            console.log("url:", "<?= $block->escapeUrl($block->getLoginUrl()) ?>");
            $(".user-icon").on("click", function () {
                location.href = "<?= $block->escapeUrl($block->getLoginUrl()) ?>";
            });
            <?php endif;?>
        });
    })
</script>

<script>
    (function () {
        const addCookie = function (name, value, expiresHours) {
            var cookieString = name + "=" + escape(value);
            //判断是否设置过期时间
            if (expiresHours > 0) {
                var date = new Date();
                date.setTime(date.getTime + expiresHours * 3600 * 1000);
                cookieString = cookieString + "; expires=" + date.toGMTString();
            }
            document.cookie = cookieString;
        }
        addCookie("login_redirect", location.href, 1);
    })()
</script>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-67067879-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-67067879-1');
</script>