<?php
/** @var TouchShop\Basic\Block\CarouselBasic $block */
?>

<link rel="stylesheet" type="text/css"
      href="<?php echo $block->getViewFileUrl('TouchShop_Basic::css/owl.carousel.min.css') ?>">
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Basic::css/owl-overwrite.css")?>">
<div class="owl-carousel-container">
    <div class="owl-carousel owl-theme">
        <?php foreach ($block->getImages() as $name => $image): ?>
            <div style="cursor: pointer" class="item" onclick="toView('<?php echo $image["url"] ?>')">
                <img style="max-height: 998px" src="<?php echo $image["src"]; ?>"/>
                <span data-color="<?php echo $image["text-color"]?>" style="display: none"></span>
            </div>
        <?php endforeach; ?>
    </div>
</div>
<script>
    function toView(params) {
        window.open(params)
    }
    (function () {
        require(["jquery", "owlcarousel"], function ($) {
            $(document).ready(function () {
                $(".owl-carousel").css("visibility", "hidden");
                var owl = $('.owl-carousel').owlCarousel({
                    loop: true,
                    margin: 10,
                    autoplay: true,
                    nav: false,
                    items: 1,
                    dots: true,
                    lazyEffect: true,
                    // dotsEach: true,
                });

                var allSpan = $(".owl-carousel.owl-theme span"),
                    spanArr = allSpan.slice(2,6),
                    navText = $(".navigation .level0 > .level-top"),
                    owlImgNum = allSpan.length - 8 ;
                console.log(owlImgNum);

                    // change color every switch
                owl.on("initialized.owl.carousel changed.owl.carousel", function (e) {
                    var index = e.relatedTarget.current();
                    console.log(index ,spanArr[(index-2) % owlImgNum].getAttribute("data-color"));
                    navText.css("color", spanArr[(index-2) % owlImgNum].getAttribute("data-color"));
                });

                <?php if ($block->isFullScreen()): ?>
                function resizeCarouselContainer() {
                    var WINDOW_WIDTH = document.body.offsetWidth
                    var TARGET_WIDTH = $('.page-main').width()
                    $('.owl-carousel-container').width(WINDOW_WIDTH)
                    $('.owl-carousel-container').css('margin-left', -((WINDOW_WIDTH - TARGET_WIDTH) / 2) + 'px')
                }

                resizeCarouselContainer()

                owl.on("refresh.owl.carousel", function () {
                    var timeout = setTimeout(function () {
                        owl.css("visibility", "visible");
                    },500);
                });

                $('.owl-carousel').owlCarousel('refresh');

                window.addEventListener('resize', function () {
                    resizeCarouselContainer()
                });
                <?php endif; ?>
            });
        });
    })();
</script>