<?php
/**@var $block TouchShop\Feedback\Block\Complain */

?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Feedback::css/feedback.css") ?>">

<div class="feedback-container">
<form action="<?php echo $block->getFormAction() ?>>" method="post" class="feedback-form">
    <div class="feedback-blank"></div>
    <div class="feedback-back">
        <img src="<?php echo $block->getBaseUrl() . 'pub/media/wysiwyg/page-back-img-top/back1.jpg'?>" alt="">
        <h2>Feedback</h2>
    </div>
    <div class="feedback-form-action-control-container">


        <div class="feedback-selection">
            <label for="feedbackCategory">Category <span>*</span></label>
            <select id="feedbackCategory">
                <option value="">--select--</option>
                <?php foreach ($block->getCategories() as $category): ?>
                    <option value="<?= $category['value'] ?>"><?= $category['label'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <label for="order">Order ID <span>*</span><small> ( If you don't have one, please contact us at <a href="mailto:ushelp@1byone.com">ushelp@1byone.com )</a> </small>
            <input name="order" id="feedBackOrder" type="text" required="required" autocomplete="off">
        </label>
        <div class="feedback-detail">

            <label for="detail">Issue Details<span>*</span>
                <textarea name="detail" id="feedbackDetail" type="text" required="required" autocomplete="off" cols="30"
                          rows="10"></textarea>
            </label>
        </div>
        <div class="feedback-form-basic-info-container">

            <label for="text">Email address <span>*</span>
                <input name="email" id="feedbackEmail" type="email" required="required" autocomplete="off">
            </label>
        </div>

        <div class="feedback-hint"></div>

        <div class="feedback-form-basic-info-container">

            <div class="feedback-pwd1">

                <label for="password">Password <span>*</span>
                    <input name="password" id="feedbackPwd1" type="password" required="required" autocomplete="off">
                </label>
            </div>

            <div class="feedback-pwd2">

                <label for="password">Please enter your Password again<span>*</span>
                    <input name="password" id="feedbackPwd2" type="password" required="required" autocomplete="off">
                </label>
            </div>
        </div>

        <div class="form-action-btn">
            <button type="button">SUBMIT</button>
        </div>
    </div>
</form>
</div>
<script>
    require(['jquery', 'ajax', 'bindQuickAutoLogin'], function ($, ajax, binder) {
        let data = <?= $block->getLoginInfo()?>;
        let hint = $(".feedback-hint");
        let category = $("#feedbackCategory");
        hint.text(sessionStorage.getItem("success") || '').css("color", "blue");
        binder.bind(
            data,
            "<?= $block->getBaseUrl()?>",
            $("#feedbackEmail"),
            $(".feedback-form-action-control-container .feedback-pwd1"),
            $(".feedback-form-action-control-container .feedback-pwd2"),
            $("#feedbackPwd1"),
            $("#feedbackPwd2"),
            $(".feedback-form-action-control-container input"),
            $(".form-action-btn button[type='button']"),
            hint,
            submitFormFun,
        );

        function submitFormFun(email, customerId) {
            let result = false;
            if(category.val() == "")
                return result;
            ajax.sendAjax(
                false,
                "<?= $block->getFormAction()?>",
                {
                    email: email,
                    // customerId: customerId,
                    order: $("#feedBackOrder").val(),
                    categoryId: category.val(),
                    detail: $("#feedbackDetail").val()
                },
                function (res) {
                    console.log("form submit", res);
                    if (res.status_code == 200) {
                        result = true;
                    } else {
                        hint.text(res.error_message);
                    }
                });
            return result;
        }
    });

</script>