<?php /** @var $block TouchShop\Support\Block\FAQTab */
$data = $block->getInfo()
?>

<?php $FAQ = $block->getFAQ(); ?>
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/faqtab.css") ?>">
<!--<a href="" id="faq"></a>-->
<div class="product-details-faq">
    <?php if (count($FAQ)): ?>
        <?php foreach ($block->getFAQ() as $index => $item): ?>
            <div class="faq-assembling <?= ($index < 10 ? '' : 'faq-assembling-more') ?> ">

                <span class="faq-toggle triangle-facing-down">
                </span>
                <div class="faq-item-panel">
                    <h1><?php echo $item['question'] ?></h1>
                    <p><?php echo $item['answer'] ?></p>
                </div>
            </div>
        <?php endforeach ?>
        <?php if (count($FAQ) > 10): ?>
            <div class="faq-more-btn">See More >></div>
        <?php endif; ?>
    <?php endif ?>
    <div class="faq-ask-btn"> Ask A Question >></div>
    <div class="faq-form-action-control-container">
        <div class="faq-form-basic-info-container">

            <label>Question <span>*</span></label>
            <textarea type="text" name="content" required="required" cols="30" rows="10"></textarea>
            <div class="hint">the required field cannot be empty</div>

            <label>Email <span>*</span></label>
            <input type="email" name="email" id="faqEmail" required="required"/>
            <div class="hint">the required field cannot be empty</div>

        </div>


        <div class="faq-hint"></div>

        <div>

            <div class="faq-pwd1">
                <label for="password">Password <span>*</span>
                    <input name="password" id="faqPwd1" type="password" required="required" autocomplete="off">
                </label>
            </div>

            <div class="faq-pwd2">
                <label for="password">Please enter your Password again<span>*</span>
                    <input name="password" id="faqPwd2" type="password" required="required" autocomplete="off">
                </label>
            </div>
        </div>
        <div class="form-action-btn">
            <button type="button">SUBMIT</button>
        </div>
    </div>
</div>

<script>
    (function () {
        require(['jquery', 'TouchShop_Touch1byone/js/formValidate'], function ($, formValidater) {
            $(document).ready(function () {
                var faqMoreBtn = $(".faq-more-btn");
                var faqAskQuestionBtn = $(".faq-ask-btn");
                var faqAssemblingMore = $(".faq-assembling-more");
                var faqForm = $(".faq-form-action-control-container");
                var isFaqFormShowed = false;
                var isMoreShowed = false;
                $("p").slideToggle(0);
                faqForm.hide();
                $(".faq-toggle").on("click", function () {
                    $(this).toggleClass("triangle-facing-up");
                    // console.log($(this).parent(".faq-assembling").find("p"));
                    $(this).parent(".faq-assembling").find("p").slideToggle(0);
                    // $(this).parent(".faq-assembling").toggleClass("back-color-grey");
                    $(document).trigger("Hchanged");
                });
                $(".faq-item-panel > h1").click(function () {
                    $(this).parent().prev().toggleClass("triangle-facing-up");
                    $(this).next().slideToggle(0);
                    $(document).trigger("Hchanged");
                });
                faqMoreBtn.click(function () {

                    if (isMoreShowed == false) {
                        faqAssemblingMore.css("display", "flex");
                        $(this).text("See More <<");
                        isMoreShowed = true;
                        formValidater.resetAreaForm(form);
                    } else {
                        faqAssemblingMore.css("display", "none");
                        $(this).text("See More >>");
                        isMoreShowed = false;
                    }
                });
                faqAskQuestionBtn.click(function () {
                    if (isFaqFormShowed == false) {
                        faqForm.show();
                        $(this).text("Ask A Question <<");
                        isFaqFormShowed = true;
                    } else {
                        faqForm.hide();
                        $(this).text("Ask A Question >>");
                        isFaqFormShowed = false;
                    }
                });
            })
        })
    })()
</script>
<script>
    require(['jquery', 'ajax', 'bindQuickAutoLogin', 'TouchShop_Touch1byone/js/formValidate'], function ($, ajax, binder, formValidater) {
        let data = <?= $block->getInfo()?>;
        let hint = $(".faq-hint");
        let form = $(".product-details-faq");

        hint.text(sessionStorage.getItem("success") || '').css("color", "blue");
        binder.bind(
            data,
            "<?= $block->getBaseUrl()?>",
            $("#faqEmail"),
            $(".faq-form-action-control-container .faq-pwd1"),
            $(".faq-form-action-control-container .faq-pwd2"),
            $("#faqPwd1"),
            $("#faqPwd2"),
            $(".faq-form-action-control-container input"),
            $(".form-action-btn button[type='button']"),
            hint,
            submitFormFun,
        );

        function submitFormFun(email) {
            formValidater.validateForm(form);
            let content = $(".faq-form-basic-info-container textarea").val();
            let result = false;
            ajax.sendAjax(
                false,
                "<?= $block->getFormAction()?>",
                {
                    email: email,
                    content: content,
                    productId: data.productId
                },
                function (res) {
                    console.log("form submit", res);
                    if (res.status_code == 200) {
                        result = true;
                    } else {
                        hint.text(res.error_message).css("color", "red");
                    }
                });
            return result;
        }
    });

</script>

