<?php
/**@var $block TouchShop\Support\Block\SupportBlock */
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/simplePagination.css") ?>">
<link rel="stylesheet"
      href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/simplePaginationOverwrite.css") ?>">
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/support.css") ?>">
<div class="catalog-panel">

    <div class="catalog-panel-blank"></div>
    <div class="catalog-panel-background">
        <img src="<?php echo $block->getBaseUrl() . 'pub/media/wysiwyg/page-back-img-top/banner_FAQ.jpg'?>" alt="" />
        <h2>FAQ <br>Manual & Drivers</h2>
    </div>
    <div class="input-group">
        <input type="text" placeholder="Search by Product Name / SKU">
        <input type="button" id="supportSearch" value="Search"/>
    </div>
    <div class="main">
        <div class="flex-container">
            <?php $index = 8; ?>
            <?php while ($index-- > 0): ?>
                <div class="flex-item">
                    <div class="post">
                        <div class="img-container">
                            <img src="" alt="" draggable="false">
                        </div>
                        <div class="des-group">
                            <h3></h3>
                            <a href="" class="catalog-faq">FAQ</a>
                            <a href="" class="catalog-manual">Manual</a>
                        </div>

                    </div>
                </div>
            <?php endwhile; ?>
        </div>
    </div>
    <div class="footer">
        <div class="pagination">
            <ul id="pagination-demo" class="pagination-sm"></ul>
        </div>
    </div>

    <div class="catalog-panel-hint"> Oops, we didn't find anything... <br/>Haven't find your answer yet? <a href="<?= $block->getBaseUrl() . 'feedback'?>">Ask us<span> ></span></a></div>
</div>

<script>
    (function () {

        require(["jquery", "simplePagination", "dotdotdot"], function ($) {
            var currentPage = 1,
                imgArr = $(".flex-item img"),
                fileContainer = $(".flex-item ul"),
                prodName = $(".flex-item .post h3"),
                closeBtn = $(".flex-item .post-cover span"),
                post = $(".flex-item .post"),
                postCover = $(".flex-item .post-cover"),
                faq = $(".flex-item .catalog-faq"),
                manual = $(".flex-item .catalog-manual"),
                prodDetails = $(".flex-item"),
                faqCover = $(".faq-cover"),
                faqInfo = $(".faq-info"),
                faqCloseBtn = $(".faq-info > span"),
                faqQ = $(".faq-info .question"),
                faqA = $(".faq-info .answer"),
                paginationItem = $(".pagination-demo ul"),
                searchInput = $(".input-group input:first-child"),
                currentPage = 1,
                isSearching = false,
                isPageIni = false,
                catalogPanelHint = $(".catalog-panel-hint");

                $(document).ready(function () {
                    console.log("require working....");
                    faqCloseBtn.on("click", function () {
                        faqCover.css("display", "none");
                    });

                    closeBtn.on("click", function () {
                        let postCover = $(this).parent();
                        postCover.css("display", "none");
                    });

                    post.on("click", function () {
                        post.next().css("display", "none");
                        let postCover = $(this).next();
                        postCover.css("display", "flex");
                    });


                    //1. page first loaded , send ajax, display result

                    sendAjax(currentPage);
                    isPageIni = true;
                    //2. click pagination item, send ajax,  finished on pagenationIni callback


                    //3. click search button , send ajax
                    $("#supportSearch").on("click", function (e) {
                        isSearching = true;
                        sendAjax(1);
                    });

                    $(document).keypress(function (e) {
                        if (e.which == 13 && searchInput.is(":focus")) {
                            e.preventDefault();
                            $("#supportSearch").click();
                        }
                    })
                });
            catalogPanelHint.css("display", "none");
            function paginatinoIni(total) {
                $("#pagination-demo").pagination({
                    items: total,
                    itemsOnPage: 6,
                    currentPage: 1,
                    cssStyle: '',
                    prevText: '<span>&laquo;</span>',
                    nextText: '<span>&raquo;</span>',
                    onPageClick: function (page, e) {
                        //2. click pagination , send ajax
                        sendAjax(page);
                    },
                })
            }

            function sendAjax(page) {
                console.log("sendAjax in");
                var responseText = $.ajax({
                    url: "<?php echo $block->getUrl('support') ?>",
                    type: "POST",
                    dataType: "json",
                    data: {
                        key: $(".input-group input[type='text']").val(),
                        page_num: page,
                        page_size: 6
                    },
                    success: function (res) {
                        console.log("ajax ok");
                        console.log(res, page);
                        display(res, page);
                    },
                    error: function (jqXHR, textstatus, errorThrown) {
                        console.log(jqXHR, textstatus, errorThrown);
                        console.log("ajax error");
                    }
                });
            }


            function display(res, currentPage) {
                // hide all posts
                post.css("display", "none");
                let total = res.total_count;

                if (total == 0) {
                    console.log("data is zero");
                    catalogPanelHint.css("display", "block");
                    $("#pagination-demo").css("display", "none");
                    $(".flex-container").css("display", "none");

                } else {
                    let productsArr = res.products;
                    let productsArrLen = productsArr.length;
                    if (isSearching || isPageIni) {
                        // twbsPagination totalPage refresh
                        //1. remove target element
                        // $("#pagination-demo").remove();
                        //2. add it from it's parent
                        // $(".footer > .pagination").append("<ul id=\"pagination-demo\" class=\"pagination-sm\"></ul>");
                        //3. re-initialize
                        paginatinoIni(total);

                        console.log("pagini");
                    }

                    isSearching = false;
                    isPageIni = false;

                    imgArr.each(function (index, ele) {

                        if (index < productsArrLen) {
                            $(post[index]).css("display", "flex");
                            $(ele).attr("src", productsArr[index].image);
                            let resHtml = "";
                            let dFiles = productsArr[index].download_files;
                            let dataPName = productsArr[index].product_name;
                            let dataFAQ = productsArr[index].faq;
                            let dataUrl = productsArr[index].url;
                            // let faqText = '';
                            // console.log(dFiles, dataPName);
                            if (dataFAQ.length == 0) {
                                $(faq[index]).css("display", "none");
                            }
                            if(dFiles.length == 0) {
                                $(manual[index]).css("display", "none");
                            }
                            $(fileContainer[index]).html(resHtml);
                            $(prodName[index]).text(dataPName);
                            $(prodName[index]).dotdotdot();
                            console.log("faq[index]:", faq[index]);
                            $(faq[index]).attr("href", dataUrl + "#faq");
                            $(manual[index]).attr("href", dataUrl + "#download_files");
                            // $(prodDetails[index]).attr("href", dataUrl);
                            $(prodDetails[index]).click(function () {
                                console.log("dataUrl: ", dataUrl);
                                location.href = dataUrl;
                            });
                        } else {
                            return false;
                        }
                    });
                }
            }
        });
    })()
</script>