<?php
/**@var $block TouchShop\Support\Block\SupportBlock */
?>

<!--this should be added globally inside head tag-->
<!--suppress JSAnnotator -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css">-->

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/bootstrap.min.css")?>">
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/support.css")?>">
<div class="catalog-panel">
    <div class="catalog-header">
        <form method="post">
            <lable>Search by Product Name/SKU</lable>
            <div class="input-group" >
                <input type="text" placeholder="find what you what ...">
                <input type="button" id="supportSearch" value="search"/>
            </div>
        </form>
    </div>
    <div class="main">
        <div class="flex-container">
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3>this is a</h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
            <div class="flex-item">
                <div class="post">
                    <img src="" alt="" draggable="false">
                    <h3></h3>
                </div>
                <div class="post-cover">
                    <a href="#">FAQ >></a>
                    <a href="#">Products Details >></a>
                    <span>x</span>
                    <h3>Download List</h3>
                    <ul>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="pagination">
            <ul id="pagination-demo" class="pagination-sm"></ul>
        </div>
    </div>

    <div class="catalog-panel-background"></div>

    <div class="faq-cover">
        <div class="faq-info">
            <span>x</span>
            <div class="faq-block">
                <div class="question"></div>
                <div class="answer"></div>
            </div>
        </div>
    </div>

</div>

<script>
    (function () {
        // var paginationClicked = false;
        require(["jquery", "twbsPagination"], function ($) {
            $(document).ready(function () {
                console.log("require working....");
                $("#supportSearch").on("click", function (e) {
                    //console.log("search clicked !",<?php //echo json_encode($products)?>//);
                    fuck(e, 1);
                });
                var currentPage = 1,
                    imgArr = $(".flex-item img"),
                    fileContainer = $(".flex-item ul"),
                    prodName = $(".flex-item .post h3"),
                    closeBtn = $(".flex-item .post-cover span"),
                    post = $(".flex-item .post"),
                    postCover = $(".flex-item .post-cover"),
                    faq = $(".flex-item .post-cover a:first-child"),
                    prodDetails = $(".flex-item .post-cover a:last-child"),
                    faqCover = $(".faq-cover"),
                    faqInfo = $(".faq-info"),
                    faqCloseBtn = $(".faq-info > span"),
                    faqQ = $(".faq-info .question"),
                    faqA = $(".faq-info .answer");

                // console.log(aArr, aArr[0]);
                faqCloseBtn.on("click", function () {
                    faqCover.css("display", "none");
                });

                closeBtn.on("click",function () {
                    // console.log("closeBtn", this);
                    let postCover= $(this).parent();
                    postCover.css("display", "none");
                });

                post.on("click", function () {
                    post.next().css("display","none");
                    // console.log("flexItem", this);
                    let postCover = $(this).next();
                    postCover.css("display", "flex");
                });
                
                // paginatinoIni(1, currentPage);

                fuck(currentPage, imgArr, fileContainer, prodName, faq, prodDetails, faqQ, faqA, faqCover);
                console.log("done");

                $("#pagination-demo").on("click",function () {
                    fuck(currentPage, imgArr, fileContainer, prodName, faq, prodDetails, faqQ, faqA, faqCover);
                });

            });

            function paginatinoIni(totalP, currentPage) {
                console.log(totalP);
                $('#pagination-demo').twbsPagination({
                    totalPages: totalP,
                    visiblePages: 7,
                    prev: "<",
                    next: ">",
                    firstClass: "first-btn",
                    lastClass: "last-btn",
                    paginationClass: "pagination-overall",
                    onPageClick: function (e, page) {
                        // fuck(e, page, imgArr, fileContainer, prodName);
                        currentPage = page;
                    },
                });
            }


            function fuck(page, imgArr, fileContainer, prodName, faq, prodDetails, faqQ, faqA, faqCover) {
                console.log("fuck in");
                console.log(page, imgArr);
                var responseText = $.ajax({
                    url: "<?php echo $block->getUrl('support') ?>",
                    type: "POST",
                    dataType: "json",
                    data: {
                        key: $(".input-group input[type='text']").val(),
                        page_num: page,
                        page_size: 8
                    },
                    success: function (res) {
                        console.log("ajax ok");
                        console.log(res);
                        display(res, imgArr, fileContainer, prodName, faq, prodDetails, faqQ, faqA, faqCover);
                    },
                    error: function (jqXHR,textstatus, errorThrown) {
                        console.log(jqXHR,textstatus,errorThrown);
                        console.log("ajax error");
                    }
                });
                // console.log(responseText,"outside");
            }

            function display(res, imgArr, fileContainer, prodName, faq, prodDetails, faqQ, faqA, faqCover) {
                // console.log(res.total, res.products);
                let total = res.total_count;
                let productsArr = res.products;
                let totalP = Math.ceil(total/8);
                paginatinoIni(totalP);
                // console.log(totalP);
                // console.log(imgArr);
                imgArr.each(function (index,ele) {
                    // console.log(ele, productArr[index].image);
                    ele.src = "../" + productsArr[index].image;
                    // console.log(ele.src);
                    let resHtml = "";
                    let dFiles = productsArr[index].download_files;
                    let dataPName = productsArr[index].product_name;
                    let dataFAQ = productsArr[index].faq;
                    let dataUrl = productsArr[index].url;
                    // console.log(dFiles, dataPName);
                    dFiles.forEach(function (ele) {
                        // console.log(ele);
                        resHtml += "<li><a href= ../"+ele.src + ">"+ ele.label + " >> </a></li>";
                    });
                    // console.log("123");
                    // console.log(fileContainer,$(fileContainer[index]),resHtml);
                    $(fileContainer[index]).html(resHtml);
                    $(prodName).text(dataPName);
                    // $(faq).attr("href", dataFAQ);
                    // console.log(faq);
                    $(faq[index]).on("click",function () {
                        console.log(faqQ,faqA);
                        faqCover.css("display", "block");
                        $(faqQ).text(dataFAQ[0].question);
                        $(faqA).text(dataFAQ[0].answer);
                    });
                    $(prodDetails).attr("href", dataUrl);
                });
            }
        });
    })()
</script>