<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("Magento_Customer::css/forgotpassword.css")?>">
<div class="account-container">
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getBaseUrl() . 'customer/account/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <div class="block-title"><strong>Forgot Your Password</strong></div>
    <fieldset class="fieldset input-container" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text"
                       value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>"
                       data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary">
                <span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="cancel" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">cancel</a>
        </div>
    </div>
</form>
</div>
<script>
    require(['jquery'], function ($) {
        $(function () {
            var mainCon = $("main#maincontent");

            mainCon.css("background-image", "url("+ "<?= $block->getBaseUrl() . 'pub/media/wysiwyg/account/account_back.jpg'?>" + ")");
        })
    })
</script>
