<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Catalog\Block\Product\View\Description $block */
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_ProductTool::css/details.css") ?>">

<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <div class="details-up-content-cover"></div>
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <div class="details-menu">
                <ul>
                    <?php foreach ($detailedInfoGroup as $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <li><a><?= $label ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="details-main">
                <?php foreach ($detailedInfoGroup as $index => $name): ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    ?>
                    <div class="data item title" id="tab-label-<?= /* @escapeNotVerified */
                    $label ?>">
                        <a class="details-tab" href="#<?= /* @escapeNotVerified */
                        $alias ?>"
                           id="tab-label-<?= $index ?>"
                        >
                            <?= $label ?>
                        </a>
                    </div>
                    <div class="details-content" id="<?= /* @escapeNotVerified */
                    $alias ?>">
                        <?= /* @escapeNotVerified */
                        $html ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>


<script>
    (function () {
        require(['jquery', 'jquery/ui'], function ($) {


            var productInfo = $(".product.info.detailed");
            var detailsMenu = $(".details-menu");
            var detailsMenuItem = $(".details-menu li");
            var doc = $(document);
            var section = $(".sections");
            // var sectionTop = 50;
            var currentStates = 'A';
            var isUp = false;
            var detailsMain = $(".details-main");
            var last = doc.scrollTop();
            var contentArr = $(".details-tab");
            var contentTopArr = [];
            // assuming that the page content offsetTop is constant
            // var contentTopArr = contentArr.offset().top;
            var detailsMenuAItem = $(".details-menu li a");
            var body = $("body");
            var isOverNum = productInfo.offset().top - doc.scrollTop() - 130;
            var sectionTop = productInfo.offset().top - 80;

            function resizeProductContainer(e) {
                var WINDOW_WIDTH = document.body.offsetWidth
                var TARGET_WIDTH = $('.page-main').width()
                e.width(WINDOW_WIDTH)
                e.css('margin-left', -((WINDOW_WIDTH - TARGET_WIDTH) / 2) + 'px')
            }

            $(document).trigger("Hchanged");
            $(document).resize(function () {
                console.log("body height:", $(this).height());
            });


            contentArr.each(function () {
                contentTopArr.push($(this).offset().top);
            })


            var len = contentTopArr.length;

            // resizeProductContainer(detailsMenu);
            var detailsMenuItemLen = detailsMenuAItem.length;
            detailsMenuItem.on("click", function (e) {


                detailsMenuAItem.css("color", "grey");
                $(e.target).css("color", "#8d131c");
                location.href = "#tab-label-" + $(this).text();

                // add 200px offset scroll distance
                var ac = $(window).scrollTop();
                console.log($(this).index() );

                //bottom situation
                if($(this).index() < detailsMenuItemLen - 1) {
                    $("body,html").animate({'scrollTop': ac - 200}, 0);
                }
            })

            $(document).on("Hchanged", function () {
                console.log("Hchanged !");
                contentTopArr = [];
                contentArr.each(function () {
                    contentTopArr.push($(this).offset().top);
                })
            })

            // page first loaded
            if (currentStates === 'A') {
                console.log("status", currentStates);
                if ((isOverNum <= -80)) {
                    section.addClass("back-normal-flow").css("top", sectionTop);
                    detailsMenu.addClass("fix-top");
                    detailsMain.css("margin-top", 90 + detailsMenu.outerHeight(true));
                    currentStates = 'C';
                }
            }

            doc.scroll(function () {

                $(detailsMenuAItem).css("color", "grey");
                var now = doc.scrollTop();
                isUp = (now > last);
                last = now;

                for (let i = len; i > 0; i--) {
                    if (now > (contentTopArr[i - 1] - 200)) {
                        $(detailsMenuAItem[i - 1]).css("color", "#8d131c");
                        // cannot use return null; will exit callback function
                        break;
                    }
                }

                isOverNum = productInfo.offset().top - doc.scrollTop() - 130;
                sectionTop = productInfo.offset().top - 80;
                if (currentStates === 'A') {
                    if (isOverNum <= 0 && isUp) {
                        section.addClass("back-normal-flow").css("top", sectionTop);
                        currentStates = 'B';
                    }
                } else if (currentStates === 'B') {
                    if (isUp && (isOverNum <= -80)) {
                        detailsMenu.addClass("fix-top");
                        detailsMain.css("margin-top", 90 + detailsMenu.outerHeight(true));
                        currentStates = 'C';
                    } else if (!isUp && (isOverNum >= 0)) {
                        section.removeClass("back-normal-flow").css("top", 50);
                        currentStates = 'A';
                    }
                } else {
                    if (!isUp && (isOverNum >= -80)) {
                        detailsMenu.removeClass("fix-top");
                        detailsMain.css("margin-top", 90 );
                        currentStates = 'B';
                    }
                }

                $(".product.data.items li").on({
                    click: function () {
                        if (currentStates === 'A') {
                            section.addClass("back-normal-flow").css("top", sectionTop);
                            detailsMenu.addClass("fix-top");
                            detailsMain.css("margin-top", 90 + detailsMenu.outerHeight(true));
                            currentStates = 'C';
                        }
                    }
                });

            });

        })
    })()
</script>