<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Catalog\Block\Product\View\Description $block */
$currentProductId = $block->getCurrentProductId();
?>

<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_ProductTool::css/details.css") ?>">

<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')): ?>
    <div class="product info detailed">
        <div class="details-up-content-cover"></div>
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <div class="details-menu">
                <ul>
                    <?php foreach ($detailedInfoGroup as $index => $name): ?>
                        <?php
                        $html = $layout->renderElement($name);
                        if (!trim($html)) {
                            continue;
                        }
                        $alias = $layout->getElementAlias($name);
                        $label = $block->getChildData($alias, 'title');
                        ?>
                        <li data-index="<?= $index?>"><a><?= $label ?></a></li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <div class="details-main">
                <?php foreach ($detailedInfoGroup as $index => $name): ?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                    $anchor = $block->getChildData($alias, 'anchor');
                    ?>
                    <div class="data item title" id="tab-label-<?= /* @escapeNotVerified */
                    $index ?>">
                        <a class="details-tab" href="#<?= /* @escapeNotVerified */
                        $alias ?>"
                           id="tab-label-<?= $index ?>"
                        >
                            <?= $label ?>
                        </a>
                        <?php if ($anchor): ?>
                            <a id="<?= $anchor ?>">
                            </a>
                        <?php endif; ?>
                    </div>
                    <div class="details-content" id="<?= /* @escapeNotVerified */
                    $alias ?>">
                        <?= /* @escapeNotVerified */
                        $html ?>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<input id="productIdValue" value="null" type="hidden"/>

<script>
    (function () {
        require(['jquery', 'jquery/ui'], function ($) {

            const TOPMENU_HEIGHT = 80;
            const NAV_HEIGHT = 34;
            const DETAILS_MENU_HEIGHT = 0;
            var productInfo = $(".product.info.detailed");
            var detailsMenu = $(".details-menu");
            var detailsMenuItem = $(".details-menu li");
            var doc = $(document);
            var section = $(".sections");
            // var sectionTop = 50;
            var currentStates = 'A';
            var isUp = false;
            var detailsMain = $(".details-main");
            var last = doc.scrollTop();
            var contentArr = $(".details-tab");
            var contentTopArr = [];
            var detailsMenuAItem = $(".details-menu li a");
            var body = $("body");
            var isOverNum = productInfo.offset().top - doc.scrollTop() - (NAV_HEIGHT + TOPMENU_HEIGHT);
            var sectionTop = productInfo.offset().top - TOPMENU_HEIGHT;
            var docHeight = doc.height();
            var windowHeight = $(window).height();
            var detailsMenuAll = $(".details-main .details-tab, .details-menu li a");
            var regexp = new RegExp(/\d+$/);
            var ankorJumpOffset = 110;

            $("#productIdValue").val(<?=$currentProductId?>);
            $(document).trigger("Hchanged");
            $(document).resize(function () {
                console.log("body height:", $(this).height());
            });
            contentArr.each(function () {
                contentTopArr.push($(this).offset().top);
            })
            var len = contentTopArr.length;
            var detailsMenuItemLen = detailsMenuAItem.length;
            detailsMenuItem.on("click", function (e) {
                detailsMenuAItem.css("color", "grey");
                $(e.target).css("color", "#e70012");
                location.href = "#tab-label-" + $(this).attr("data-index");
                // add 200px offset scroll distance
                var ac = $(window).scrollTop();

                //bottom situation,
                if (docHeight - windowHeight + 200 < contentTopArr[$(this).index()]) {
                    console.log("last one");
                } else {
                    $("body,html").animate({'scrollTop': ac - ankorJumpOffset}, 0);
                }
            });


            $(document).on("Hchanged", function () {
                console.log("Hchanged !");
                contentTopArr = [];
                docHeight = doc.height();
                contentArr.each(function () {
                    contentTopArr.push($(this).offset().top);
                });
            })

            // page first loaded
            if (currentStates === 'A') {
                if ((isOverNum <= -TOPMENU_HEIGHT)) {
                    section.addClass("back-normal-flow").css("top", sectionTop);
                    detailsMenu.addClass("fix-top");
                    detailsMain.css("margin-top", DETAILS_MENU_HEIGHT + detailsMenu.outerHeight(true));
                    currentStates = 'C';
                }
            }


            detailsMenuAll.each(function (index, e) {
                $(e).text().trim();
                console.log($(e).text(), $(e).text().trim().match(regexp));
                if ($(e).text().trim().match(regexp)) {
                    let arr = $(e).text().trim().split(" ");
                    console.log(arr);
                    let arrr = arr.slice(0, arr.length - 1);
                    $(e).text(arrr.join(" "));
                }
            });


            doc.scroll(function () {
                console.log("scrolled");
                $(detailsMenuAItem).css("color", "grey");
                var now = doc.scrollTop();
                isUp = (now > last);
                last = now;

                for (let i = len; i > 0; i--) {
                    if (now > (contentTopArr[i - 1] - ankorJumpOffset)) {
                        $(detailsMenuAItem[i - 1]).css("color", "#e70012");
                        // cannot use return null; will exit callback function
                        break;
                    }
                }

                isOverNum = productInfo.offset().top - doc.scrollTop() - (NAV_HEIGHT + TOPMENU_HEIGHT);
                sectionTop = productInfo.offset().top - TOPMENU_HEIGHT;
                if (currentStates === 'A') {
                    if (isOverNum <= 0 && isUp) {
                        section.addClass("back-normal-flow").css("top", sectionTop);
                        currentStates = 'B';
                    }
                } else if (currentStates === 'B') {
                    if (isUp && (isOverNum <= -TOPMENU_HEIGHT)) {
                        detailsMenu.addClass("fix-top");
                        detailsMain.css("margin-top", DETAILS_MENU_HEIGHT + detailsMenu.outerHeight(true));
                        currentStates = 'C';
                    } else if (!isUp && (isOverNum >= 0)) {
                        section.removeClass("back-normal-flow").css("top", NAV_HEIGHT);
                        currentStates = 'A';
                    }
                } else { // 'C' => 'B'
                    if (!isUp && (isOverNum >= -TOPMENU_HEIGHT)) {
                        detailsMenu.removeClass("fix-top");
                        detailsMain.css("margin-top", DETAILS_MENU_HEIGHT);
                        currentStates = 'B';
                    }
                }


                // 'A' => 'C'
                $(".product.data.items li").on({
                    click: function () {
                        if (currentStates === 'A') {
                            section.addClass("back-normal-flow").css("top", sectionTop);
                            detailsMenu.addClass("fix-top");
                            detailsMain.css("margin-top", DETAILS_MENU_HEIGHT + detailsMenu.outerHeight(true));
                            currentStates = 'C';
                        }
                    }
                });


                // 'C' => 'A'
                $(".back-top").click(function () {
                    if (currentStates === 'C') {
                        section.removeClass("back-normal-flow").css("top", NAV_HEIGHT);
                        detailsMain.css("margin-top", DETAILS_MENU_HEIGHT);
                        detailsMenu.removeClass("fix-top");
                        currentStates = 'A';
                    }
                });


            });

        })
    })()
</script>