<?php /**@var $block TouchShop\ReviewTool\Block\Product\View\ListView */ ?>
<!--<link rel="stylesheet" href="--><?php //echo $block->getViewFileUrl("TouchShop_Support::css/bootstrap.min.css") ?><!--">-->
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/simplePagination.css") ?>">
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_ReviewTool::css/list.css") ?>">
<?php
//$reviews = $block->getReviewData();
$reviews = [
    'page_num' => 3,
    'total' => 1000,
    'reviews_data' => [
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['https://t-ec.bstatic.com/images/hotel/max1280x900/101/101291604.jpg', 'https://cdn.pixabay.com/photo/2017/06/03/22/02/landscape-2369863_960_720.jpg', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],

        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['', '', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['https://t-ec.bstatic.com/images/hotel/max1280x900/101/101291604.jpg', 'https://cdn.pixabay.com/photo/2017/06/03/22/02/landscape-2369863_960_720.jpg', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['', '', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['https://t-ec.bstatic.com/images/hotel/max1280x900/101/101291604.jpg', 'https://cdn.pixabay.com/photo/2017/06/03/22/02/landscape-2369863_960_720.jpg', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['', '', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['https://t-ec.bstatic.com/images/hotel/max1280x900/101/101291604.jpg', 'https://cdn.pixabay.com/photo/2017/06/03/22/02/landscape-2369863_960_720.jpg', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ],
        [
            'star' => 4,
            'title' => "this products is very good",
            'videos_url' => ['https://images-na.ssl-images-amazon.com/images/I/B19CXRwrp%2BS.mp4'],
            'images_url' => ['', '', ''],
            'comment' => 'lalalallal fjasofj f a jf; jas j jfdruoewf;kfj liu ni  fhao al fjasdjfop l jopj  ;l jpoi ;lfj  ni lhao wo de lmingZI ',
            'author' => "baozi",
            'date' => "2017/8/09 12:00",
        ]
    ]
];
?>
<div>123</div>
<div class="reviews-customize">
    <div class="reviews-list">
        <ul class="reviews-items">
            <?php foreach ($reviews['reviews_data'] as $item): ?>
                <li class="reviews-item">
                    <div class="reviews-heading">
                        <div class="reviews-rating">

                            <div class="rating-result rating-background">
                                <ul>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                </ul>
                            </div>
                            <div class="rating-result">
                                <ul>
                                    <?php while ($item['star']-- > 0): ?>
                                        <li class="star-five"></li>
                                    <?php endwhile; ?>
                                </ul>
                            </div>
                        </div>

                        <div class="reviews-title"><?= $item['title'] ?></div>
                    </div>

                    <div class="reviews-media">
                        <?php foreach ($item['videos_url'] as $video_url): ?>
                            <div class="reviews-media-item">
                                <video controls="controls" preload="auto">
                                    <source src="<?= $video_url ?>"
                                            type="video/<?= substr($video_url, strrpos($video_url, '.') + 1) ?>">
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                        <?php endforeach; ?>
                        <?php foreach ($item['images_url'] as $img_url): ?>
                            <div class="reviews-media-item" style="background-image: url('<?= $img_url ?>/*')">
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="reviews-flex-text">
                        <p class="reviews-content"><?= $item['comment'] ?></p>
                        <div class="reviews-details"><span><strong><?= $item['author'] ?></strong></span> published at
                            <time><?= $item['date'] ?></time>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <div class="pagination">
        <ul id="pagination-review" class="pagination-sm"></ul>
    </div>
</div>


<script>
    (function () {
        require(['jquery', 'simplePagination'], function ($) {

            $(function () {
                console.log(123);
                console.log("total:", <?= $reviews['total']?>);
                paginatinoIni(<?= $reviews['total']?>);
                paginatinoIni(1000);
            });

            function sendAjax(page) {
                console.log("sendAjax in");
                var id = $("#productIdValue").val();
                $.ajax({
                    url: "<?php echo $block->getBaseUrl() . "reviews/ajax/reviewList"?>",
                    type: "POST",
                    dataType: "json",
                    data: {
                        id : id,
                        page_num: page,
                        page_size: 2
                    },
                    success: function (res) {
                        console.log("ajax ok");
                        console.log(res, page);
                        display(res, page);
                    },
                    error: function (jqXHR, textstatus, errorThrown) {
                        console.log(jqXHR, textstatus, errorThrown);
                        console.log("ajax error");
                    }
                });
            };


            function paginatinoIni(total) {
                $("#pagination-review").pagination({
                    items: total,
                    itemsOnPage: 8,
                    currentPage: <?php echo $reviews['page_num']?>,
                    cssStyle: '',
                    prevText: '<span>&laquo;</span>',
                    nextText: '<span>&raquo;</span>',
                    onPageClick: function (page, e) {
                        //2. click pagination , send ajax
                        console.log("page:",page);
                        sendAjax(page);
                    },
                })
            }
        })
    })()
</script>





