<?php /**@var $block TouchShop\ReviewTool\Block\Product\View\ListView */ ?>
<!--<link rel="stylesheet" href="--><?php //echo $block->getViewFileUrl("TouchShop_Support::css/bootstrap.min.css") ?><!--">-->
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_Support::css/simplePagination.css") ?>">
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl("TouchShop_ReviewTool::css/list.css") ?>">
<?php
$reviews = $block->getReviewData();

?>

<div class="reviews-customize">
    <div class="reviews-list">
        <ul class="reviews-items">
            <?php foreach ($reviews['reviews_data'] as $item): ?>
                <li class="reviews-item">
                    <div class="reviews-heading">
                        <div class="reviews-rating">

                            <div class="rating-result rating-background">
                                <ul>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                    <li class="star-five"></li>
                                </ul>
                            </div>
                            <div class="rating-result">
                                <ul>
                                    <?php while ($item['star']-- > 0): ?>
                                        <li class="star-five"></li>
                                    <?php endwhile; ?>
                                </ul>
                            </div>
                        </div>

                        <div class="reviews-title"><?= $item['title'] ?></div>
                    </div>

                    <div class="reviews-media">
                        <?php foreach ($item['videos_url'] as $video_url): ?>
                        <?php if($video_url != ''):?>
                            <div class="reviews-media-item">
                                <video controls="controls" preload="auto">
                                    <source src="<?= $video_url ?>"
                                            type="video/<?= substr($video_url, strrpos($video_url, '.') + 1) ?>">
                                    Your browser does not support the video tag.
                                </video>
                            </div>
                        <?php endif;?>
                        <?php endforeach; ?>
                        <?php foreach ($item['images_url'] as $img_url): ?>
                        <?php if($img_url != ''):?>
                            <div class="reviews-media-item" style="background-image: url('<?= $img_url ?>')">
                            </div>
                        <?php endif;?>
                        <?php endforeach; ?>
                    </div>
                    <div class="reviews-flex-text">
                        <p class="reviews-content"><?= $item['comment'] ?></p>
                        <div class="reviews-details"><span><strong><?= $item['author'] ?></strong></span> published at
                            <time><?= $item['date'] ?></time>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="pagination">
        <ul id="pagination-review" class="pagination-sm"></ul>
    </div>

</div>

<?php if ($reviews['total'] > 0):?>
<script>
    (function () {
        require(['jquery', 'simplePagination'], function ($) {
            $(function () {
                paginatinoIni(<?= $reviews['total']?>);
            });
            function sendAjax(page) {
                console.log("sendAjax in");
                var id = $("#productIdValue").val();
                $.ajax({
                    url: "<?php echo $block->getBaseUrl() . "reviews/ajax/reviewList"?>",
                    type: "POST",
                    // dataType: "json",
                    data: {
                        id : id,
                        page_num: page,
                        page_size: 10
                    },
                    success: function (res) {
                        console.log("ajax ok");
                        $("#product-review-container").html(res);
                        $(".details-menu.fix-top a:contains('Reviews')").trigger("click");
                    },
                    error: function (jqXHR, textstatus, errorThrown) {
                        console.log(jqXHR, textstatus, errorThrown);
                        console.log("ajax error");
                    }
                });
            };

            function paginatinoIni(total) {
                $("#pagination-review").pagination({
                    items: total,
                    itemsOnPage: 8,
                    currentPage: <?php echo $reviews['page_num']?>,
                    cssStyle: '',
                    prevText: '<span>&laquo;</span>',
                    nextText: '<span>&raquo;</span>',
                    onPageClick: function (page, e) {
                        //2. click pagination , send ajax
                        console.log("page:",page);
                        sendAjax(page);
                    },
                })
            }
        })
    })()
</script>
<?php endif;?>




