ygframe:
  demo:
    listen_port: '55440'
  globals:
    hbase:
      hbase_host: 192.168.0.201
    mysql:
      mysql_url: mysql+mysqldb://root:123456@192.168.0.16/ygfbad_db
    redis:
      default_expire: '7776000'
      redis_host: 192.168.0.23
      redis_password: ''
      redis_port: '6379'
