ygframe:
  demo:
    listen_port: int
  globals:
    mysql:
      mysql_url:
    redis:
      default_expire: int
      redis_host:
      redis_password:
      redis_port: int
    hbase:
      hbase_host: