<?php
/**
 * Created by PhpStorm.
 * User: jing
 * Date: 4/1/18
 * Time: 9:08 PM
 */

namespace TouchShop\ReviewTool\Block\Product\View;


use Magento\Framework\View\Element\Template;

class ListView extends Template
{
    public function toHtml()
    {
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }

}